name: MarkdownParse JUnit Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile and run our JUnit tests, also test out echo
        run: |
          echo The directory is: $GITHUB_WORKSPACE
          javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar MarkdownParseTest.java MarkdownParse.java
          java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore MarkdownParseTest

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
